name: gnn_deep_learning
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.9
    - numpy=1.26.0
    - tqdm=4.66.1
    - pyyaml=6.0.1
    - torchvision=0.16.0
    - black=23.10.1
    - pylint=3.0.2
    - tensorboard=2.15.0
    - pandas=2.1.2
    - opencv=4.8.1
    - matplotlib=3.8.0
    - wandb=0.15.12
