name: gnn_dl_cpu
channels:
    - defaults
    - pytorch
    - nvidia
    - pyg
    - conda-forge
dependencies:
    - python=3.9
    - pytorch=2.1.0=py3.9_0
    - torchaudio=2.1.0
    - pyg=2.4.0=py39_torch_2.1.0_cpu
    - numpy=1.26.0
    - pyyaml=6.0.1
    - torchvision=0.16.0
    - black=24.2.0
    - pylint=3.0.2
    - tensorboard=2.15.0
    - pandas=2.1.2
    - opencv=4.8.1
    - matplotlib=3.8.0
    - wandb=0.15.12
    - torch-scatter
