# This file acts as the base configuration file for the project.
# See configs/template.yaml for an example how to create a deviating configuration file
# By default the config/user.yaml configuration file is used.

# used for naming purposes
note: "init"

#######################################################################################
################################### MODEL PARAMETERS ##################################
#######################################################################################

# the type of solution to run
model_type: "entropic_gcn"
dataset: "planetoid"

model_parameters:
  basic_gcn:
    pretrained_weights: null
    depth: 16
    hidden_dim: 16
  entropic_gcn:
    pretrained_weights: null
    hidden_dim: 16
    temperature: 1
    weight: 0.001

conv_block_args:
  # can be in [basic_gcn]
  block_type: "basic_gcn"
  basic_gcn:
    dropout_rate: 0.0
fusion_block_args:
  # can be in [sum, mean]
  block_type: "mean"
transform_block_args:
  # can be in [id, full]
  block_type: "id"
  linear:
    depth: 2
    hidden_dim: 256


#######################################################################################
################################## DATASET PARAMETERS #################################
#######################################################################################

dataset: "planetoid"
dataset_parameters:
  planetoid:
    name: "Cora"


#######################################################################################
######################################## OTHER ########################################
#######################################################################################

hyperparameters:
  train:
    batch_size: 4096
    learning_rate: 0.001
    weight_decay: 0
    epochs: 100
    save_every: 10
  val:
    batch_size: 4096
    val_every: 20

# device on which to train
device: "cpu"

# whether to resume training from earlier model
resume_training: False

# paths are relative from project_root_directory
subpaths:
  data: "resources/data/"
  cache: "resources/cache/"
  logs: "resources/logs/"
  output: "resources/output/"
  resume_from: "path/to/weights"
  pretrained_weights: "resources/pretrained_weights"

save_names:
  weights: "weights.pth"
  optimizer: "optimizer.pth"
  pretrained_metadata: "pretrained_metadata.json"

wandb:
  enable: False
  entity: "gnn_dl"
  project: "Init Tests"
  group: "Start"

logging:
  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  console: "DEBUG"
  wandb: "DEBUG"