name: Check format with isort
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: isort/isort-action@master
        with:
            requirementsFiles: "environment.yml"
